version: '3.8'

# Define the services
services:
  script-over-tcp:
    image: script-over-tcp
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: ["poetry", "run", "python"]
